package Beans;
// Generated 2017-jan-18 18:27:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by hbm2java
 */
public class Car  implements java.io.Serializable {


     private Integer idCar;
     private String carRegnumber;
     private String carType;
     private String carHome;
     private String carlocation;
     private String carImage;
     private int dailyPrice;
     private Set bookings = new HashSet(0);

    public Car() {
    }

	
    public Car(String carRegnumber, String carType, String carHome, String carlocation, String carImage, int dailyPrice) {
        this.carRegnumber = carRegnumber;
        this.carType = carType;
        this.carHome = carHome;
        this.carlocation = carlocation;
        this.carImage = carImage;
        this.dailyPrice = dailyPrice;
    }
    public Car(String carRegnumber, String carType, String carHome, String carlocation, String carImage, int dailyPrice, Set bookings) {
       this.carRegnumber = carRegnumber;
       this.carType = carType;
       this.carHome = carHome;
       this.carlocation = carlocation;
       this.carImage = carImage;
       this.dailyPrice = dailyPrice;
       this.bookings = bookings;
    }
   
    public Integer getIdCar() {
        return this.idCar;
    }
    
    public void setIdCar(Integer idCar) {
        this.idCar = idCar;
    }
    public String getCarRegnumber() {
        return this.carRegnumber;
    }
    
    public void setCarRegnumber(String carRegnumber) {
        this.carRegnumber = carRegnumber;
    }
    public String getCarType() {
        return this.carType;
    }
    
    public void setCarType(String carType) {
        this.carType = carType;
    }
    public String getCarHome() {
        return this.carHome;
    }
    
    public void setCarHome(String carHome) {
        this.carHome = carHome;
    }
    public String getCarlocation() {
        return this.carlocation;
    }
    
    public void setCarlocation(String carlocation) {
        this.carlocation = carlocation;
    }
    public String getCarImage() {
        return this.carImage;
    }
    
    public void setCarImage(String carImage) {
        this.carImage = carImage;
    }
    public int getDailyPrice() {
        return this.dailyPrice;
    }
    
    public void setDailyPrice(int dailyPrice) {
        this.dailyPrice = dailyPrice;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }




}


