package EntityBeans;
// Generated 2017-jan-16 15:21:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Office generated by hbm2java
 */
public class Office  implements java.io.Serializable {


     private Integer idOffice;
     private String officeName;
     private String officeAdress;
     private String officeLocation;
     private String officePhone;
     private Set bookings = new HashSet(0);

    public Office() {
    }

	
    public Office(String officeName, String officeAdress, String officeLocation, String officePhone) {
        this.officeName = officeName;
        this.officeAdress = officeAdress;
        this.officeLocation = officeLocation;
        this.officePhone = officePhone;
    }
    public Office(String officeName, String officeAdress, String officeLocation, String officePhone, Set bookings) {
       this.officeName = officeName;
       this.officeAdress = officeAdress;
       this.officeLocation = officeLocation;
       this.officePhone = officePhone;
       this.bookings = bookings;
    }
   
    public Integer getIdOffice() {
        return this.idOffice;
    }
    
    public void setIdOffice(Integer idOffice) {
        this.idOffice = idOffice;
    }
    public String getOfficeName() {
        return this.officeName;
    }
    
    public void setOfficeName(String officeName) {
        this.officeName = officeName;
    }
    public String getOfficeAdress() {
        return this.officeAdress;
    }
    
    public void setOfficeAdress(String officeAdress) {
        this.officeAdress = officeAdress;
    }
    public String getOfficeLocation() {
        return this.officeLocation;
    }
    
    public void setOfficeLocation(String officeLocation) {
        this.officeLocation = officeLocation;
    }
    public String getOfficePhone() {
        return this.officePhone;
    }
    
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }




}


